version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      typescript-eslint-deps:
        patterns:
          - "typescript-eslint"
          - "@typescript-eslint*"
      commitlint-deps:
        patterns:
          - "@commitlint*"
      docusaurus-deps:
        patterns:
          - "@docusaurus*"
