import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docs: [
    "index",
    {
      "User guide": [
        "user-guide/installation-and-usage",
        "user-guide/configuration",
        "user-guide/ignore-code",
        {
          type: "category",
          label: "Rules",
          items: [
            "user-guide/rules/list",
            {
              type: "category",
              label: "List",
              items: [
                {
                  type: "autogenerated",
                  dirName: "user-guide/rules/list"
                }
              ]
            }
          ]
        }
      ],
      "Developer Guide": ["developer-guide/custom-parser", "developer-guide/plugins"]
    }
  ]
};

export default sidebars;
