module.exports = {
  "raw-ignore-regex": false,
  "spec-char-escape": false,
  "text-ignore-regex": false,
  "attr-bans": [
    "align",
    "background",
    "bgcolor",
    "border",
    "frameborder",
    "longdesc",
    "marginwidth",
    "marginheight",
    "scrolling",
    "style",
    "width"
  ],
  "indent-delta": false,
  "indent-style": "tabs",
  "indent-width": 4,
  "indent-width-cont": false,
  "tag-bans": [
    "style",
    "b",
    "i"
  ],
  "tag-close": true,
  "tag-name-lowercase": true,
  "tag-name-match": true,
  "tag-self-close": false,
  "doctype-first": true,
  "doctype-html5": true,
  "attr-name-style": "dash",
  "attr-name-ignore-regex": /^[0-9a-o]+$/,
  "attr-no-dup": true,
  "attr-no-unsafe-char": true,
  "attr-order": [
    "id",
    "class"
  ],
  "attr-quote-style": "double",
  "attr-req-value": true,
  "attr-new-line": 1,
  "attr-validate": true,
  "id-no-dup": true,
  "id-class-no-ad": true,
  "id-style": "underscore",
  "id-class-style": "underscore",
  "class-no-dup": true,
  "class-style": "lowercase",
  "id-class-ignore-regex": false,
  "img-req-alt": true,
  "img-req-src": true,
  "html-valid-content-model": true,
  "head-valid-content-model": true,
  "href-style": "relative",
  "link-req-noopener": true,
  "label-req-for": true,
  "line-end-style": "lf",
  "line-no-trailing-whitespace": true,
  "line-max-len": 80,
  "line-max-len-ignore-regex": false,
  "head-req-title": true,
  "title-no-dup": true,
  "title-max-len": 60,
  "html-req-lang": true,
  "lang-style": "case",
  "fig-req-figcaption": false,
  "focusable-tabindex-style": false,
  "input-radio-req-name": true,
  "input-req-label": false,
  "table-req-caption": false,
  "table-req-header": false,
  "tag-req-attr": false
};
